algoritmo "AconselhaPrograma"
// Função :
// Autor :
// Data : 23/02/2019
// Seção de Declarações 
var
Dinheiro: Real

inicio
// Seção de Comandos
Escreval("***Serviço Informatizado de Sugestões***")
Escreva("Quanto dinheiro você tem sobrando? ")
Leia(Dinheiro)
Se Dinheiro >= 10 entao
   Escreval("Vá ao cinema hoje à noite.")
Senao
     Escreval("Fique em casa vendo TV.")
Fimse
     Escreva("Obrigado e volte sempre.")
 
fimalgoritmo
