algoritmo "aconselhaPrograma"
// Função :
// Autor :
// Data : 12/04/2020
// Seção de Declarações 
var
   Dinheiro: Real

inicio
// Seção de Comandos
   Escreval("*** Serviço Informatizado de Sugestões ***")
   Escreva("Qaunto Dinheiro você tem Sobrando? ")
   Leia(Dinheiro)
   Se (Dinheiro >= 10)entao
      Escreval("Vá ao Cinema hoje à Noite!!!")
   Senao
        Escreval("Fique em Casa vendo TV!!!")
   FimSe
        Escreva("Obrigado e Volte Sempre!!!")

fimalgoritmo
