algoritmo "CalculoDeMediaAritmetica"
// Função :
// Autor :
// Data : 15/12/2018
// Seção de Declarações 
var
   A, B, Media: Real
inicio
// Seção de Comandos
   Escreval("Programa que calcula a media aritmetica de dois valores.")
   Escreva("Digite um valor: ")
   Leia(A)
   Escreva("Digite um outr valor: ")
   Leia(B)
   Media <- (A + B)/2
   Escreva("A media dos dois valores eh: ", Media)

 
fimalgoritmo
