algoritmo "calculoMediaAritmetica"
// Função :
// Autor :
// Data : 12/04/2020
// Seção de Declarações 
var
   A, B, Media: Real

inicio
// Seção de Comandos
   Escreval("-----------------------------------------------------------------")
   Escreval("Programa que Calcula a Média Aritmética de dois Valores.")
   Escreval("-----------------------------------------------------------------")
   Escreva("Digite um Valor: ")
   Leia(A)
   Escreva("Digite outro Valor: ")
   Leia(B)
   Media := (A + B) / 2
   Escreval("--------------------------------------------")
   Escreval("A Média dos dois Valores é: ", Media:4:1)
   Escreval("----------------------------------------------")


fimalgoritmo
