algoritmo "Condicao"
// Função :
// Autor :
// Data : 30/03/2020
// Seção de Declarações 
var
   a: Inteiro
inicio
// Seção de Comandos
   escreva("Digite o Valor de A: ")
   leia(a)
   se (a > 10) entao
      escreval("O Valor de A é: ", a)
   senao
        se (a = 10) entao
           escreval("O Valor de A é Igual a 10!")

        senao
             escreval("O Valor de A não é Maior a 10!")
        fimse
   fimse


fimalgoritmo
