algoritmo "valoresPares"
// Função :
// Autor :
// Data : 27/02/2019
// Seção de Declarações 
var
   CONT, V: Inteiro
inicio
// Seção de Comandos
  //Para C <- 10 ate 1 passo -1 faca
        //EscrevaL(C)
   
   //FimPara
   Escreva("Digite um valor: ")
   Leia(V)
   Se(V % 2 = 1) entao
        V <- V -1
   FimSe
   Para CONT <- V ate 0 passo -2 faca
        Escreval(CONT)
   
   
   FimPara

 
fimalgoritmo
