algoritmo "ConteAte10"
// Função :
// Autor :
// Data : 26/02/2019
// Seção de Declarações 
var
   valor, contador, salto: Inteiro
inicio
// Seção de Comandos
   contador <- 0
   Escreva("Quer contar até quanto? ")
   Leia(valor)
   Escreva("Qual será o valor do salto? ")
   Leia(salto)
   Enquanto (contador <= valor) faca
            Escreval(contador)
            contador <- contador + salto
   
   FimEnquanto


 
fimalgoritmo
