algoritmo "Cálculo de Média Aritmética"
// Função :
// Autor :
// Data : 23/02/2019
// Seção de Declarações 
var
X, Y, Media: Real

inicio
// Seção de Comandos 
Escreva("Programa que calcula a média aritmética de dois valores.")
Escreval()
Escreval()
Escreva("Digite um valor: ")
Leia(X)
Escreva("Digite outro valor: ")
Leia(Y)
Media <- (X + Y) / 2
Escreval()
Escreval()
Escreva("A média dos dois valores é: ", Media)






fimalgoritmo
