algoritmo "Delta"
// Função : Calcular o valor de Delta.
// Autor : João Marcos
// Data : 05/01/2020
// Seção de Declarações 
var
   delta, a, b, c: Inteiro
   

inicio
// Seção de Comandos

   escreva("Entre com o Valor de a: ")
   leia(a)
   escreva("Entre com o Valor de b: ")
   leia(b)
   escreva("Entre com o Valor de c: ")
   leia(c)
   delta <- b*b - 4*a*c
   escreval("O valor de Delta é: ", delta)
 
fimalgoritmo
