algoritmo "DesvioCondicional"
// Função :
// Autor :
// Data : 14/03/2019
// Seção de Declarações 
var
   nome: Caracter
inicio
// Seção de Comandos
   Escreva("Informe seu nome: ")
   Leia(nome)
   Se (nome = "João Marcos") entao
      Escreva("Você é o Diretor de Infraestrutura de TI!")
   senao
        Escreva("Você não é o Diretor de Infraestrutra de TI!")
   
   FimSe

 
fimalgoritmo
