algoritmo "EnquantoFaca"
// Função :
// Autor :
// Data : 14/03/2019
// Seção de Declarações 
var
   contador: Inteiro

inicio
// Seção de Comandos
   contador <- 1
   enquanto contador <= 10 faca
       escreval(contador)
       contador <- contador + 1
   fimenquanto

   escreval()
   contador <- 1
   repita
       escreval(contador)
       contador <- contador + 1
   ate contador >= 10
   
fimalgoritmo
