algoritmo "FazSomaProcedimento"
// Função :
// Autor :
// Data : 02/03/2019
// Seção de Declarações 
var
   X, Y: Inteiro

Procedimento Soma(A, B: Inteiro)
inicio
      Escreval("Recebi o valor ", A)
      Escreval("Recebi o valor ", B)
      Escreval("A soma entre os dois é: ", A + B)


FimProcedimento

inicio
// Seção de Comandos
   X <- 5
   Y <- 3
   Soma (X, Y)
fimalgoritmo
