algoritmo "fazSomaProcedimento"
// Função :
// Autor :
// Data : 10/04/2020
// Seção de Declarações 
var
X, Y: Inteiro
Procedimento Soma(A, B: Inteiro)

inicio
      Escreval("Recebi o Valor: ", A)
      Escreval("Recebi o Valor: ", B)
      Escreval("A Soma entre os Dois Valores é: ",  A + B)

FimProcedimento

inicio
// Seção de Comandos

   X := 5
   Y := 3
   Soma(X, Y)


fimalgoritmo
