algoritmo "FritarUmOvo"


inicio

// Versão 1
Colocar um ovo na frigideira
Esperar o ovo ficar frito
Remover o ovo da frigideira

// Versão 2
Retirar um ovo da geladeira
Colocar a frigideira no fogo
Colocar óleo
Esperar até o óleo ficar quente
Quebrar o ovo seprando a casca
Colocar o conteúdo do ovo na frigideira
Esperar um minuto
Retirar o ovo da frigideira
Apagar o fogo



fimalgoritmo
