algoritmo "funcionario"
// Função :
// Autor :
// Data : 03/04/2020
// Seção de Declarações 
var
   funcionario:vetor[0..4]de caractere
   i: inteiro

inicio
// Seção de Comandos
   para i de 0 ate 4 faca
    escreva("Digite o Nome ", i+1,  " : ")
    leia(funcionario[i])
   fimpara
   escreval()
   para i de 0 ate 4 faca
    escreval(funcionario[i])
   fimpara

 
fimalgoritmo
