algoritmo "LeiaNome-exerc01"
// Função : Ler nome e sobrenome e em seguinda imprime o nome completo na tela.
// Autor : João Marcos
// Data : 05/01/2020
// Seção de Declarações 
var
   nome, sobrenome: Caractere

inicio
// Seção de Comandos 
   escreva("Digite o seu Nome: ")
   leia(nome)
   escreva("Digite o seu Sobrenome: ")
   leia(sobrenome)
   
   escreval()
   escreval("O seu Nome Completo é: ", nome, " ", sobrenome)


fimalgoritmo
