algoritmo "NumeroPrimo"
// Função : crie um algoritmo que leia um numero inteiro e diga se ele é primo ou não.
// Autor :
// Data : 19/01/2020
// Seção de Declarações 
var
   num: Inteiro

inicio
// Seção de Comandos

   escreva("Digite um Valor: ")
   leia(num)
   se (num / 1 = num) e  (num / num = 1) entao
      escreval("O Valor", num, " É PRIMO!")
   senao
        escreval("O Valor", num, "NÃO É PRIMO1")
   fimse


fimalgoritmo
