algoritmo "ParouImpar"
// Função : Ler um número e dizer se ele é par ou ímpar.
// Autor : João Marcos
// Data : 06/01/2020
// Seção de Declarações 
var
   N1: Inteiro

inicio
// Seção de Comandos
   escreva("Digite um Número: ")
   leia(N1)
   
   se (N1 % 2 = 0) entao
      escreval("O Número ", N1, " é PAR!")
   senao
        escreval("O Número ", N1, " é ÍMPAR!")
   fimse

 
fimalgoritmo
