algoritmo "QueimaouNaoQueima"
// Função :
// Autor :
// Data : 02/01/2020
// Seção de Declarações 
var
   nome: Caractere
   idade: Inteiro



inicio
// Seção de Comandos 
   Escreva("Digite o seu Nome: ")
   Leia(nome)
   Escreva("Digite a sua idade: ")
   Leia(idade)
   Se (idade >= 18)entao
      Escreval("Esse Não Queima!!!")
   Senao
        Escreval("QUEIMA!!!")
   Fimse
fimalgoritmo
