algoritmo "somaFuncao"
// Função :
// Autor :
// Data : 11/04/2020
// Seção de Declarações 
var
V1, V2, S: Inteiro
Funcao Soma(X, Y: Inteiro): Inteiro
var
inicio
      Retorne X + Y
FimFuncao
inicio
// Seção de Comandos 
   Escreva("Digite o Primeiro Valor: ")
   Leia(V1)
   Escreva("Digite o Segundo Valor: ")
   Leia(V2)
   S := Soma(V1, V2)
   Escreval("A Soma entre ", V1, " e ", V2, " é igual a:", S)


fimalgoritmo
