algoritmo "testeVetor"
// Função :
// Autor :
// Data : 11/04/2020
// Seção de Declarações 
var
   v: vetor[1..10] de Inteiro
   c: Inteiro

inicio
// Seção de Comandos 
   Para c := 1 ate 10 passo 1 faca
        Escreva("Digite o", c, "o. Valor: ")
        Leia(v[c])
   FimPara
   
   Para c := 1 ate 10 passo 1 faca
        Escreva("[",v[c] , "]")
   
   FimPara

fimalgoritmo
