algoritmo "TriploPositivo-exerc01"
// Autor :
// Data : 05/01/2020
// Seção de Declarações 
var
   numero, triplo: Inteiro

inicio
// Seção de Comandos
   escreva("Digite um número inteiro positivo: ")
   leia(numero)
   Se (numero > 0)entao
      triplo:= numero * 3
      escreval()
      escreval("O Triplo do Número ", numero, " é igual a: ", triplo)
   Senao
        escreval("Este Número não é um Número Inteiro Positivo!")
   Fimse


 
fimalgoritmo
